In [31]:
import numpy as np
import math
from sklearn.linear_model import LogisticRegression
num_samps = 10000
num_feats = 3

In [32]:
X = np.random.rand(num_samps,num_feats)
y = (np.random.randint(2,size=num_samps))
print(X, y)

[[0.53374178 0.21114549 0.47989091]
 [0.35302113 0.35492059 0.4818109 ]
 [0.62305309 0.51320242 0.67276034]
 ...
 [0.98761715 0.33206781 0.42312158]
 [0.2939278  0.17449793 0.69265994]
 [0.4547369  0.9144372  0.79734879]] [0 0 1 ... 0 0 1]


In [33]:
print(y)


[0 0 1 ... 0 0 1]


In [34]:
clf = LogisticRegression().fit(X,y) #supervised
clf.coef_

array([[ 0.03628197,  0.10652413, -0.01400001]])

In [35]:
x_new = np.random.rand(1,num_feats)
y_new = np.random.randint(2)
clf.predict(x_new)

array([1])

In [36]:
clf.score(X,y)

0.5078